=== lablup/backend.ai/src/ai/backend/web/static/resources/theme.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "fontFamily": {
      "type": "string",
      "description": "The font family applied to both light and dark themes."
    },
    "light": {
      "$ref": "./antdThemeConfig.schema.json"
    },
    "dark": {
      "$ref": "./antdThemeConfig.schema.json"
    },
    "logo": {
      "type": "object",
      "description": "Properties to customize the site's logo, considering both light and dark modes.",
      "properties": {
        "src": {
          "type": "string",
          "description": "The source of the logo image."
        },
        "srcCollapsed": {
          "type": "string",
          "description": "The source of the collapsed logo image."
        },
        "srcDark": {
          "type": "string",
          "description": "The source of the logo image in dark mode."
        },
        "srcCollapsedDark": {
          "type": "string",
          "description": "The source of the collapsed logo image in dark mode."
        },
        "alt": {
          "type": "string",
          "description": "The alt text for the logo image."
        },
        "href": {
          "type": "string",
          "description": "The URL that the logo links to."
        },
        "size": {
          "width": {
            "type": "number",
            "description": "The width of the logo image."
          },
          "height": {
            "type": "number",
            "description": "The height of the logo image."
          }
        },
        "sizeCollapsed": {
          "width": {
            "type": "number",
            "description": "The width of the collapsed logo image."
          },
          "height": {
            "type": "number",
            "description": "The height of the collapsed logo image."
          }
        }
      }
    },
    "sider": {
      "type": "object",
      "properties": {
        "theme": {
          "type": ["string"],
          "enum": ["dark", "light", "auto"],
          "default": "auto",
          "description": "The theme of the sider. If it's set to 'dark' or 'light', the entered theme will be applied to the sider regardless of the site's dark mode status."
        }
      }
    },
    "branding": {
      "type": "object",
      "properties": {
        "companyName": {
          "type": "string",
          "description": "The name of the company or organization."
        },
        "brandName": {
          "type": "string",
          "description": "The name of the brand or product."
        }
      }
    }
  },
  "required": ["$schema", "light", "dark", "logo", "sider"]
}

=== lablup/backend.ai/src/ai/backend/web/static/resources/theme.json
{
  "$schema": "./theme.schema.json",
  "fontFamily": "'Ubuntu', Roboto, sans-serif",
  "light": {
    "token": {
      "colorPrimary": "#FF7A00",
      "colorLink": "#FF7A00",
      "colorText": "#141414",
      "colorInfo": "#028DF2",
      "colorError": "#FF4D4F",
      "colorSuccess": "#00BD9B",
      "screenXLMax": 1919,
      "screenXXLMin": 1920,
      "screenXXL": 1920
    },
    "components": {
      "Tag": {
        "borderRadiusSM": 1
      },
      "Layout": {
        "lightSiderBg": "#FFF",
        "siderBg": "#141414",
        "headerBg": "#FF9729"
      },
      "Divider": {
        "colorSplit": "#D9D9D9"
      },
      "Table": {
        "headerBg": "#E3E3E3",
        "headerSplitColor": "rgba(0,0,0,0.25)"
      }
    }
  },
  "dark": {
    "token": {
      "colorPrimary": "#DC6B03",
      "colorLink": "#DC6B03",
      "colorText": "#FFF",
      "colorInfo": "#009BDD",
      "colorError": "#DC4446",
      "colorSuccess": "#03A487",
      "colorFillSecondary": "#262626",
      "screenXLMax": 1919,
      "screenXXLMin": 1920,
      "screenXXL": 1920
    },
    "components": {
      "Tag": {
        "borderRadiusSM": 1
      },
      "Layout": {
        "lightSiderBg": "#FFF",
        "siderBg": "#141414",
        "headerBg": "#E88A28"
      }
    }
  },
  "logo": {
    "src": "/manifest/backend.ai-webui-white.svg",
    "srcCollapsed": "/manifest/backend.ai-brand-simple-white.svg",
    "srcDark": "/manifest/backend.ai-webui-black.svg",
    "srcCollapsedDark": "/manifest/backend.ai-brand-simple-black.svg",
    "alt": "Backend.AI Logo",
    "href": "/start",
    "size": {
      "width": 159,
      "height": 24
    },
    "sizeCollapsed": {
      "width": 34,
      "height": 34
    },
    "aboutModalSize": {
      "width": 159,
      "height": 24
    }
  },
  "sider": {},
  "branding": {
    "companyName": "Lablup Inc.",
    "brandName": "Backend.AI"
  }
}
